### ISSUE TITLE
Understanding hasPrevPage & hasNextPage

### ISSUE THREAD

**Issue by EDjur** [charlie-hadden/kysely-paginate#29]
Hi!

I've started looking into this library and I'm impressed so far - nice work! Super cool and easy to use with Kysely.

I'm looking into replacing my own custom built cursor-based pagination with this. But I have a question regarding hasPrevPage.

In the following test you have, shouldn't `hasPrevPage` be `true`? Since you're basically requesting page 2 of this table?

Essentially I want to know: How should I let the client know that they can go back by sending the `startCursor` as `before`?

Or what does `undefined` mean for these values?

Test for reference:
https://github.com/charlie-hadden/kysely-paginate/blob/ed37a87ad9c940596fc44e6b590d6d9ba6289b8d/test/cursor.test.ts#L102

Thanks again!

**Comment by charlie-hadden** [comment]
Hi there,

The reason I return undefined in that case is mainly a performance one. It is quite easy to check if there's a next page by over-fetching by one result, and discarding it from the returned result set. It is a bit trickier to tell if there are any results _before_ the cursor provided. It might be a nice addition to add an option to support that.

When I use this library myself I'll typically show a previous button in my UI if `hasPreviousPage` is true, or if an `after` cursor is provided. This strictly speaking isn't correct as the cursor could point to a non-existent record that would come before the first record in the results, which is why the library returns `undefined`, but is good enough for most practical use cases. Obviously similar logic applies to the `hasNextPage` value when paginating backwards with `after`.

Hopefully that explains it for you but let me know if not.

**Comment by EDjur** [comment]
Hi,

Thanks for the response! 

> When I use this library myself I'll typically show a previous button in my UI if hasPreviousPage is true, or if an after cursor is provided.

I see, that's quite nifty.

In my own implementation (that I unfortunately made before we started using kysely) I basically have the tie-breaker clause set to fetch the cursor element OR greater (`>=`) when paginating forward. With a +2 limit you can then figure out if there is a previous page as well.

But I like your approach since it's quite simple.

**Comment by EDjur** [comment]
With that said, it could be cool to have an option where the library handles everything for you without needing to have this client-side or extra server-side logic. I might look into the code a bit too see if it's an easy change

**Comment by EDjur** [comment]
Hey,

I looked into this a bit but I just went with your suggestion instead since it started to get quite messy to get this into the lib.

I'll close this now. I got what I needed, thank you! :)
